from typing import Protocol
from .models import (
    MainDishText,
    SideDishMedia,
    DrinkStyle,
    TextVariant,
    PrintJob,
    BarcodeMapping,
)


class MainDishTextRepository(Protocol):
    def create_maindishtext(self, item: MainDishText) -> MainDishText: ...
    def get_maindishtext(self, item_id: int) -> MainDishText | None: ...
    def update_maindishtext(self, item_id: int, item: MainDishText) -> bool: ...
    def delete_maindishtext(self, item_id: int) -> bool: ...


class SideDishMediaRepository(Protocol):
    def create_sidedishmedia(self, item: SideDishMedia) -> SideDishMedia: ...
    def get_sidedishmedia(self, item_id: int) -> SideDishMedia | None: ...
    def update_sidedishmedia(self, item_id: int, item: SideDishMedia) -> bool: ...
    def delete_sidedishmedia(self, item_id: int) -> bool: ...


class DrinkStyleRepository(Protocol):
    def create_drinkstyle(self, item: DrinkStyle) -> DrinkStyle: ...
    def get_drinkstyle(self, item_id: int) -> DrinkStyle | None: ...
    def update_drinkstyle(self, item_id: int, item: DrinkStyle) -> bool: ...
    def delete_drinkstyle(self, item_id: int) -> bool: ...


class TextVariantRepository(Protocol):
    def create_textvariant(self, item: TextVariant) -> TextVariant: ...
    def get_textvariant(self, item_id: int) -> TextVariant | None: ...
    def update_textvariant(self, item_id: int, item: TextVariant) -> bool: ...
    def delete_textvariant(self, item_id: int) -> bool: ...


class PrintJobRepository(Protocol):
    def create_printjob(self, item: PrintJob) -> PrintJob: ...
    def get_printjob(self, item_id: int) -> PrintJob | None: ...
    def update_printjob(self, item_id: int, item: PrintJob) -> bool: ...
    def delete_printjob(self, item_id: int) -> bool: ...


class BarcodeMappingRepository(Protocol):
    def create_barcodemapping(self, item: BarcodeMapping) -> BarcodeMapping: ...
    def get_barcodemapping(self, item_id: int) -> BarcodeMapping | None: ...
    def update_barcodemapping(self, item_id: int, item: BarcodeMapping) -> bool: ...
    def delete_barcodemapping(self, item_id: int) -> bool: ...
